---
- name: Update n1 servers
  hosts: n1

  tasks:
  - name: Create Directory
    ansible.builtin.file:
      path: /home/ec2-user/ecommerce_docs
      state: directory

  - name: install httpd
    yum:
      name: httpd
      state: present
    become: true
...
