---
- name: install http server
  hosts: apt-server

  tasks:
  - name: install apache2
    apt:
      name: apache2
      state: present

  - name: start apache2
    service:
      name: apache2
      state: started

  - name: enable apache
    service:
      name: apache2
      enabled: true
