---
- name: update status page
  copy:
    src: static.html
    dest: /var/www/html/static.html

- name: update static Page
  template:
    src: dynamic.j2
    dest: /var/www/html/dynamic.html
...
